Program a 11th septemper 2019
DmitryInd/Univirsity-Programs pull request #1
Opened 2019-09-18 18:49 UTC by DmitryInd

Эта попытка была залита в контест под id 21342876.

Программа сначала считывает всю строку, а потом последовательно обрабатывает её символы.

2019-09-20 19:39 UTC, Mrkol requested changes
Всё, что связано с твоей IDE (visual studio) и скомпиленные бинарники проги нужно добавить в файл.gitignore. Этих файлов в репозитории быть не должно, только код.

2019-09-21 21:26 UTC, DmitryInd commented
Убрал временные файлы, добавил .gitignore.

2019-09-23 10:23 UTC, Mrkol requested changes

2019-09-23 10:23 UTC, Mrkol commented on Program 1/Program 1/main.cpp
> +	int* pi = new int[p.size() + 1];
Сишные массивы мы не используем, особенно с динамическим размером. Меняем на std::array, если размер можно задать на этапе компиляции, иначе — std::vector.

2019-09-23 10:23 UTC, Mrkol commented on Program 1/Program 1/main.cpp
> +#include <string.h>
Просто \<string\>.

2019-09-23 10:23 UTC, Mrkol commented on Program 1/Program 1/main.cpp
> +int pre_function(const std::string& p, int* pi, int i, char& now) {
Любые изменяемые глобальные состояния программы — зло. У тебя now  меняется в цикле, и каждый последующий вызов функции зависит от предыдущего. Это плохо, это надо выпилить.

2019-09-23 10:23 UTC, Mrkol commented on Program 1/Program 1/main.cpp
> +	std::cin >> str;
Атятя, теперь у тебя не O(p) памяти, как требуется в условии. Входную строку целиком нельзя хранить.

2019-09-23 15:46 UTC, DmitryInd commented on Program 1/Program 1/main.cpp
> +	std::cin >> str;
Об этом знаю.
Однако, если попеременно водить и выводить, то на 7 тесте происходит некий глюк, из-за которого поток ввода не заканчивается и программа завершается TL error'ом.
Данная проблема наблюдается, как минимум, в нашей группе, и решается либо считыванием строки сразу, либо выводом ответа в конце (а хранение ответа занимает ещё больше места).
Семинарист согласился не учитывать память, потраченную на считывание.

P. S. В моей программе видно, что изначально она писалась для посимвольного считывания, но TL в 7 тесте победил.

2019-09-23 15:48 UTC, DmitryInd commented on Program 1/Program 1/main.cpp
> +int pre_function(const std::string& p, int* pi, int i, char& now) {
Не до конца понял проблему.

2019-09-24 20:36 UTC, Mrkol commented on Program 1/Program 1/main.cpp
> +	std::cin >> str;
Нет там никакого глюка, просто потоки в плюсах действительно настолько медленные

2019-09-24 21:00 UTC, Mrkol requested changes

2019-09-24 21:00 UTC, Mrkol commented on Program 1/Program 1/main.cpp
> +int pre_function(const std::string& p, int* pi, int i, char& now) {
Хорошо, давай переформулируем так: я смотрю на этот метод, и я не понимаю, что он делает. Я не понимаю, что это за параметры (кстати за названия аргументов p, i, pi, now тоже бан, да), я не могу в голове уследить, как меняется состояние now/empty по мере вызова этой функции в цикле. Сделай проще

2019-09-29 13:35 UTC, DmitryInd commented
Поправил вроде всё, что вы просили

2019-09-29 16:44 UTC, Mrkol requested changes

2019-09-29 16:44 UTC, Mrkol commented on Program 1/Program 1/main.cpp
> +	std::string pattern;
Слишком много кода в мейне, оформи всё это дело по-человечески в разные функции.

2019-09-29 16:44 UTC, Mrkol commented on Program 1/Program 1/main.cpp
> +int pre_function(const std::string& pattern, std::vector<int>& prefix_value,
Чёт какая-то совсем мутная функция. И названия переменных мутные. Длинные названия != хорошие названия.

2019-09-29 16:44 UTC, Mrkol commented on Program 1/Program 1/main.cpp
> +			int answer = i - 2 * pattern.size() + 1;
Чево?? Так, короче, перепиши всю задачу чтобы нормально было. И юзай пробелы а не табы пожалуйста, это фигню не возможно в ревьюшнице читать с такими дикими отступами.

2019-09-29 16:53 UTC, DmitryInd commented on Program 1/Program 1/main.cpp
> +int pre_function(const std::string& pattern, std::vector<int>& prefix_value,
Просто получение значения префикс функции для некоторого элемента. Так как я не храню всю строку, то индексы букв в массиве значений префикс функции и в строке не синхронизованы. Поэтому в функцию подаётся символ, индекс,в который будет положено значение префикс функции, и где хранится значение префикс функции  предыдущего символа. Последнее нужно, чтобы была одна префикс функция и для паттерна, и для строки: у паттерна значение префикс функции предыдущего символа хранится в предыдущей "ячейке", а у строки в той же.

2019-09-29 16:55 UTC, DmitryInd commented on Program 1/Program 1/main.cpp
> +			int answer = i - 2 * pattern.size() + 1;
Переносил, чтобы строки были не очень длинными. Обычно это везде требуют, не ожидал подвоха с tab'ами.

2019-10-09 15:13 UTC, merged